#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '🏗️👷 Styling your project before committing👷‍♂️🏗️'
echo 'please be patient, this may take a while...'

# Check ESLint Standards
pnpm lint ||
(
    echo '🔨❌ Yoo, you have a problem in your code. Check linter 🔨❌
    Run pnpm lint, add changes and try commit again.';
    false;
)

echo '🏗️👷 Building your project before committing👷‍♂️🏗️'
echo 'please be patient, this may take a while...'

# Check builds
pnpm build ||
(
    echo '🔨❌ Yoo, you have a problem in your code. Check builds 🔨❌
    Run pnpm build, add changes and try commit again.';
    false;
)

echo '🎉 No error found: committing this now.... ✨🚀🏄‍♂️🍻'

npx lint-staged
